#!/bin/sh
executable=./brainfuck
test_dir=./tests
[ -x ./brainfuck ] || { printf 'No %s executable available\n' "$executable" >&2; exit 1; }

colordiff=cat
command -v colordiff >/dev/null && colordiff=colordiff

cleanup() {
    rm -f -- "$output"
}
output=
trap cleanup EXIT
trap 'exit 1' INT HUP TERM PIPE
output=$(mktemp) || exit

accept_failures=false
valgrind=

escape=$(printf \\033)

# Writes to global "reason", "error", "failed"
test_file() {
    local script expected
    script=$1 expected=$2
    shift 2

    eval "$valgrind $executable"' "$@" "$script"' >"$output" || { reason=error; error=true; return 2; }
    cmp -s "$output" "$expected" || { reason=fail; failed=true; return 1; }
    reason=OK
    return 0
}

# Writes to global "failures", "count"
test_and_compare() {
    local script expected
    script=$1 expected=$2 why=$3
    shift 3

    error=false
    failed=false

    test_file "$script" "$expected" "$@"
    printf '%s %20s: %s\n' "$why" "${f#"$test_dir"/}" "$reason"

    if $failed || $error; then
        failures=$((failures + 1))
        if ! $error; then
            echo 'Difference between expected and actual output:'
            diff -u "$expected" "$output" | sed "s/$escape/^[/g" | "$colordiff"
            $accept_failures && cp "$output" "$expected"
        fi
    fi

    count=$((count + 1))
}

while [ "$#" != 0 ]; do
    case $1 in
        (--accept-failures | -f)
            accept_failures=true;;
        (--valgrind | -v)
            valgrind='valgrind -q --leak-check=full';;
        (--valgrind=* | -v=*)
            valgrind=${1#*=};;
        (*)
            printf 'Unknown argument %s\n' "$1" >&2
            exit 1
            ;;
    esac
    shift
done

count=0 failures=0
for f in "$test_dir"/*.bf; do
    expected=${f%.bf}.out
    [ -e "$expected" ] && test_and_compare "$f" "$expected" RUN

    expected=${f%.bf}.ast
    [ -e "$expected" ] && test_and_compare "$f" "$expected" AST --no-execute --dump-tree

    expected=${f%.bf}.ops
    [ -e "$expected" ] && test_and_compare "$f" "$expected" OPS --no-execute --dump-opcodes
done

if [ "$failures" -eq 0 ]; then
    printf 'All passed, out of %s tests.\n' "$count"
    exit 0
else
    printf '%s of %s tests failed.\n' "$failures" "$count"
    exit 1
fi
